version: "3.8"
services:
  app:
    working_dir: /workspace/app
    entrypoint: bash ./entrypoint.sh
    volumes: 
      - ./app:/workspace/app
  api:
    working_dir: /src
    entrypoint: bash ./entrypoint.sh 
    volumes:
      - ./api:/src
    ports:
      - 8866:5000
  web:
    working_dir: /app
    entrypoint: bash ./entrypoint.sh
    volumes:
      - ./web:/app
    ports:
      - 7007:6655
  db:
    volumes:
      - ./prod:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 24152:5432
